name: Estilo

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  check_style:
    name: Verificar Estilo de Código
    runs-on: ubuntu-latest

    steps:
      - name: Conferir repositório
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Evita clones rasos

      - name: Criar arquivo .env
        run: |
          touch .env
          echo POSTGRES_HOST=db >> .env
          echo POSTGRES_DB=library_db >> .env
          echo POSTGRES_USER=postgres >> .env
          echo POSTGRES_PASSWORD=password >> .env
          cat .env
      - name: Executar flake8  
        run: sudo docker-compose run library_back flake8
      
      - name: Executar checagem do Prettier
        run: sudo docker-compose run library_front yarn checkFormat

      - name: Executar checagem do ESLint
        run: sudo docker-compose run library_front yarn lint

      
