name: Testes

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  check_style:
    name: Verificar Testes
    runs-on: ubuntu-latest

    steps:
      - name: Conferir repositório
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Evita clones rasos

      - name: Criar arquivo .env
        run: |
          touch library_back/.env
          echo POSTGRES_HOST=db >> library_back/.env
          echo POSTGRES_DB=library_db >> library_back/.env
          echo POSTGRES_USER=postgres >> library_back/.env
          echo POSTGRES_PASSWORD=password >> library_back/.env
          echo POSTGRES_PORT=5432 >> library_back/.env
          cat library_back/.env
      
      - name: Executar pytest  
        run: sudo docker-compose run library_back python3 ./manage.py 
      
      - name: Executar teste 
        run: sudo docker-compose run library_front yarn test --coverage --watchAll=false

      
